### ISSUE TITLE
TypeError: __classPrivateFieldGet(...).resolve is not a function

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-node#124]
## Notes

This test is disabled in `appmap-js/packages/cli/tests/unit/sequenceDiagram.spec.ts`. Please re-enable the test when this bug is fixed.

## Error report

```
➜  cli git:(feat/navie-cli-2) ✗ npx appmap-node yarn jest tests/unit/sequenceDiagram.spec.ts
(Λ) Running with appmap-node version 2.18.0
(Λ) Using config file /Users/kgilpin/source/appland/appmap-js/packages/cli/appmap.yml
(Λ) Detected Jest. Tests will be automatically recorded.
 FAIL  tests/unit/sequenceDiagram.spec.ts (36.744 s)
  ● sequence diagram command › PNG format › is generated

    TypeError: __classPrivateFieldGet(...).resolve is not a function

      at IsolatedWorld.<anonymous> (node_modules/puppeteer-core/lib/cjs/puppeteer/common/IsolatedWorld.js:707:65)
      at IsolatedWorld.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at IsolatedWorld.setContext (node_modules/puppeteer-core/lib/cjs/puppeteer/common/IsolatedWorld.js:705:36)
      at FrameManager._FrameManager_onExecutionContextCreated (node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:732:11)
      at node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:531:109
      at node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:32:11
          at Array.map (<anonymous>)
      at Object.emit (node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:31:25)
      at CDPSessionImpl.<anonymous> (node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:201:20)
      at CDPSessionImpl.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at CDPSessionImpl.emit (node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:200:36)
      at CDPSessionImpl.<anonymous> (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:758:14)
      at CDPSessionImpl.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at CDPSessionImpl._onMessage (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:747:36)
      at Connection.<anonymous> (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:607:19)
      at Connection.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Connection.onMessage (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:575:36)
      at WebSocket.<anonymous> (node_modules/puppeteer-core/lib/cjs/puppeteer/common/NodeWebSocketTransport.js:108:26)
      at node_modules/ws/lib/event-target.js:444:16
      at record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at callListener (node_modules/ws/lib/event-target.js:440:34)
      at WebSocket.onMessage (node_modules/ws/lib/event-target.js:385:9)
      at Receiver.<anonymous> (node_modules/ws/lib/websocket.js:1248:22)
      at Receiver.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Receiver.receiverOnMessage (node_modules/ws/lib/websocket.js:1247:34)
      at Receiver.<anonymous> (node_modules/ws/lib/receiver.js:513:16)
      at Receiver.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Receiver.dataMessage (node_modules/ws/lib/receiver.js:489:36)
      at Receiver.<anonymous> (node_modules/ws/lib/receiver.js:467:19)
      at Receiver.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Receiver.getData (node_modules/ws/lib/receiver.js:445:36)
      at Receiver.<anonymous> (node_modules/ws/lib/receiver.js:320:24)
      at Receiver.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Receiver.startLoop (node_modules/ws/lib/receiver.js:302:36)
      at Receiver.<anonymous> (node_modules/ws/lib/receiver.js:274:12)
      at Receiver.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Receiver._write (node_modules/ws/lib/receiver.js:270:36)
      at Socket.<anonymous> (node_modules/ws/lib/websocket.js:1292:37)
      at Socket.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Socket.socketOnData (node_modules/ws/lib/websocket.js:1291:34)

  ● sequence diagram command › PNG format › is generated

    TypeError: deferredInitPromise.reject is not a function

      at node_modules/puppeteer-core/src/common/NetworkManager.ts:322:26

  ● sequence diagram command › PNG format › is generated

    TypeError: __classPrivateFieldGet(...).resolved is not a function

      at IsolatedWorld.<anonymous> (node_modules/puppeteer-core/lib/cjs/puppeteer/common/IsolatedWorld.js:713:72)
      at IsolatedWorld.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at IsolatedWorld.hasContext (node_modules/puppeteer-core/lib/cjs/puppeteer/common/IsolatedWorld.js:712:36)
      at FrameManager._FrameManager_onExecutionContextCreated (node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:726:113)
      at node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:531:109
      at node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:32:11
          at Array.map (<anonymous>)
      at Object.emit (node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:31:25)
      at CDPSessionImpl.<anonymous> (node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:201:20)
      at CDPSessionImpl.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at CDPSessionImpl.emit (node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:200:36)
      at CDPSessionImpl.<anonymous> (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:758:14)
      at CDPSessionImpl.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at CDPSessionImpl._onMessage (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:747:36)
      at Connection.<anonymous> (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:607:19)
      at Connection.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Connection.onMessage (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:575:36)
      at WebSocket.<anonymous> (node_modules/puppeteer-core/lib/cjs/puppeteer/common/NodeWebSocketTransport.js:108:26)
      at node_modules/ws/lib/event-target.js:444:16
      at record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at callListener (node_modules/ws/lib/event-target.js:440:34)
      at WebSocket.onMessage (node_modules/ws/lib/event-target.js:385:9)
      at Receiver.<anonymous> (node_modules/ws/lib/websocket.js:1248:22)
      at Receiver.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Receiver.receiverOnMessage (node_modules/ws/lib/websocket.js:1247:34)
      at Receiver.<anonymous> (node_modules/ws/lib/receiver.js:513:16)
      at Receiver.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Receiver.dataMessage (node_modules/ws/lib/receiver.js:489:36)
      at Receiver.<anonymous> (node_modules/ws/lib/receiver.js:467:19)
      at Receiver.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Receiver.getData (node_modules/ws/lib/receiver.js:445:36)
      at Receiver.<anonymous> (node_modules/ws/lib/receiver.js:320:24)
      at Receiver.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Receiver.startLoop (node_modules/ws/lib/receiver.js:302:36)
      at Receiver.<anonymous> (node_modules/ws/lib/receiver.js:274:12)
      at Receiver.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Receiver._write (node_modules/ws/lib/receiver.js:270:36)
      at Socket.<anonymous> (node_modules/ws/lib/websocket.js:1292:37)
      at Socket.record (../../node_modules/appmap-node/src/recorder.ts:33:24)
      at Socket.socketOnData (node_modules/ws/lib/websocket.js:1291:34)

  ● sequence diagram command › PNG format › is generated

    thrown: "Exceeded timeout of 30000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      45 |         const diagram = unparseDiagram(diagramData);
      46 |         expect(diagram.rootActions).toHaveLength(2);
    > 47 |       },
         |     ^
      48 |       30 * 1000 // Allow time to install and run the headless browser
      49 |     );
      50 |   });

      at tests/unit/sequenceDiagram.spec.ts:47:5
      at tests/unit/sequenceDiagram.spec.ts:46:3
      at Object.<anonymous> (tests/unit/sequenceDiagram.spec.ts:20:1)
```

**Comment by dividedmind** [comment]
Yeah, I suppose. @kgilpin, please reopen if you see it again.
