### ISSUE TITLE
Failed tests aren't reported when they are recorded by appmap-node

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-node#133]
Example: https://github.com/getappmap/appmap-js/actions/runs/8148289801/job/22270831493

<img width="483" alt="Screen Shot 2024-03-22 at 10 51 43 AM" src="https://github.com/getappmap/appmap-node/assets/86395/0f87a518-aa92-459a-9a44-8d7bd21ae483">

Test failures should be reported, instead it says "All tests passed".

**Comment by dividedmind** [comment]
I don't think this is a bug. These tests didn't run at all (there was a compile error), so no AppMaps were generated. Please reopen if you think it's a mistake.

**Comment by dividedmind** [comment]
@kgilpin could you elaborate what would you want to see here? None of the other agents make AppMaps for test files which can't be compiled, so I don't know what the expected behavior should be.

**Comment by kgilpin** [comment]
I never see test failure reports with appmap node

I don’t have a URL handy.

**Comment by dividedmind** [comment]
I think it might be a bug in appmap-js: I checked and appmap-node definitely reports failures with Jest (even if lacking some details); there are tests for that. We'll have to dig into this a bit further.

**Comment by dividedmind** [comment]
Yeah, it seems like it's a bug in appmap-js, see for example [this test run](https://github.com/getappmap/appmap-js/actions/runs/8290941422/job/22689881296):
```
Warning: Command "appmap compare-report --source-url https://github.com/getappmap/appmap-js/blob/7270903a8b12148bc4cd930668b40eb2bd0ace09 --appmap-url https://getappmap.com/github_artifact?owner=getappmap&repo=appmap-js&run_id=8290941422&base_revision=3d9f7a57b95fb92b51e21340ba9d6d8efd9c0dc3&head_revision=7270903a8b12148bc4cd930668b40eb2bd0ace09 .appmap/change-report/3d9f7a57b95fb92b51e21340ba9d6d8efd9c0dc3-7270903a8b12148bc4cd930668b40eb2bd0ace09" exited with failure code 1
Warning: TypeError: Cannot read properties of undefined (reading 'split')
    at source_url (/snapshot/appmap-js/packages/cli/built/report/urlHelpers.js)
    at TestFailure.source_link (/snapshot/appmap-js/packages/cli/built/report/urlHelpers.js)
    at TestFailure.wrapper (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at eval (eval at createFunctionContext (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:13:112)
    at prog (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
    at execIteration (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.wrapper (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at eval (eval at createFunctionContext (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:11:49)
    at Object.prog [as fn] (/snapshot/appmap-js/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
```

It seems like it's expecting properties which aren't required by the spec. They need to eventually get emitted by appmap-node, but independent of that appmap-js needs to be able to accept all well-formed AppMaps. I'm going to move this to the *appmap-js* repo; I believe the missing data is already tracked by #110 here.
