### ISSUE TITLE
app-map node crashes

### ISSUE THREAD

**Issue by antrianis** [getappmap/appmap-node#150]
I tried to start my node app using
npx appmap-node yarn <my node app command>
but it crashes with:

  throw err;
    ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, node_assert_1.default)(this.stream)

    at Recording.emit (<localDir>\npm-cache\_npx\c76987c9a3c183fa\node_modules\appmap-node\dist\Recording.js:147:35)
    at Recording.httpClientResponse (<localDir>\npm-cache\_npx\c76987c9a3c183fa\node_modules\appmap-node\dist\Recording.js:93:14)
    at <localDir>\npm-cache\_npx\c76987c9a3c183fa\node_modules\appmap-node\dist\hooks\http.js:108:31
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (<localDir>\npm-cache\_npx\c76987c9a3c183fa\node_modules\appmap-node\dist\hooks\http.js:106:28)
    at Object.onceWrapper (node:events:631:28)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='  throw err;
    ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, node_assert_1.default)(this.stream)

    at Recording.emit (<localDir>\npm-cache\_npx\c76987c9a3c183fa\node_modules\appmap-node\dist\Recording.js:147:35)
    at Recording.httpClientResponse (<localDir>\npm-cache\_npx\c76987c9a3c183fa\node_modules\appmap-node\dist\Recording.js:93:14)
    at <localDir>\npm-cache\_npx\c76987c9a3c183fa\node_modules\appmap-node\dist\hooks\http.js:108:31
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (<localDir>\npm-cache\_npx\c76987c9a3c183fa\node_modules\appmap-node\dist\hooks\http.js:106:28)
    at Object.onceWrapper (node:events:631:28)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='

**Comment by zermelo-wisen** [comment]
@antrianis, can you try again with the latest version with the fix. It should print the current version as 2.21.1. 

```
$ npx appmap-node yarn
(Λ) Running with appmap-node version 2.21.1
```
