### ISSUE TITLE
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value: (0, node_assert_1.default)(!exports.recording.running)

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-node#34]
In `appmap-js` in `packages/cli` if I run:
```
npx appmap-node@latest yarn test installCommand
```
I get this ouptut:
```
(Λ) Running with appmap-node version 2.3.2
(Λ) Detected Jest. Tests will be automatically recorded.
 FAIL  tests/unit/agentInstall/installCommand.spec.ts
  ● Test suite failed to run

    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

      (0, node_assert_1.default)(!exports.recording.running)

      at start (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/recorder.ts:65:9)
      at eventHandler (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/hooks/jest.ts:50:12)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.238 s, estimated 6 s
```

**Comment by dividedmind** [comment]
Can't reproduce with 2.5.0 anymore, can you retry?
