### ISSUE TITLE
`RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-node#45]
To reproduce: in `appmap-js`, run the following command in `packages/cli`:
```
npx appmap-node@latest yarn test fingerprinter
```
You'll get this output:
```
(Λ) Running with appmap-node version 2.5.1
(Λ) Detected Jest. Tests will be automatically recorded.
 FAIL  tests/unit/fingerprint/fingerprinter.spec.ts
  ● Fingerprinter › rejects appmaps that are too large

    RangeError: Maximum call stack size exceeded



      at stringify (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:27:17)
      at parameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:12:12)
      at optParameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:32:10)
      at makeCallEvent (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/event.ts:20:27)
      at Recording.functionCall (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/Recording.ts:37:32)
      at FileTooLargeError.record (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/recorder.ts:22:26)
      at FileTooLargeError.get message [as message] (src/fingerprint/fileTooLargeError.ts:86:36)
      at stringify (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:27:17)
      at parameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:12:12)
      at optParameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:32:10)
      at makeCallEvent (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/event.ts:20:27)
      at Recording.functionCall (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/Recording.ts:37:32)
      at FileTooLargeError.record (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/recorder.ts:22:26)
      at FileTooLargeError.get message [as message] (src/fingerprint/fileTooLargeError.ts:86:36)
      at stringify (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:27:17)
      at parameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:12:12)
      at optParameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:32:10)
      at makeCallEvent (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/event.ts:20:27)
      at Recording.functionCall (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/Recording.ts:37:32)
      at FileTooLargeError.record (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/recorder.ts:22:26)
      at FileTooLargeError.get message [as message] (src/fingerprint/fileTooLargeError.ts:86:36)
      at stringify (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:27:17)
      at parameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:12:12)
      at optParameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:32:10)
      at makeCallEvent (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/event.ts:20:27)
      at Recording.functionCall (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/Recording.ts:37:32)
      at FileTooLargeError.record (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/recorder.ts:22:26)
      at FileTooLargeError.get message [as message] (src/fingerprint/fileTooLargeError.ts:86:36)
      at stringify (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:27:17)
      at parameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:12:12)
      at optParameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:32:10)
      at makeCallEvent (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/event.ts:20:27)
      at Recording.functionCall (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/Recording.ts:37:32)
      at FileTooLargeError.record (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/recorder.ts:22:26)
      at FileTooLargeError.get message [as message] (src/fingerprint/fileTooLargeError.ts:86:36)
      at stringify (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:27:17)
      at parameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:12:12)
      at optParameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:32:10)
      at makeCallEvent (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/event.ts:20:27)
      at Recording.functionCall (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/Recording.ts:37:32)
      at FileTooLargeError.record (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/recorder.ts:22:26)
      at FileTooLargeError.get message [as message] (src/fingerprint/fileTooLargeError.ts:86:36)
      at stringify (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:27:17)
      at parameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:12:12)
      at optParameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:32:10)
      at makeCallEvent (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/event.ts:20:27)
      at Recording.functionCall (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/Recording.ts:37:32)
      at FileTooLargeError.record (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/recorder.ts:22:26)
      at FileTooLargeError.get message [as message] (src/fingerprint/fileTooLargeError.ts:86:36)
      at stringify (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:27:17)
      at parameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:12:12)
      at optParameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:32:10)
      at makeCallEvent (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/event.ts:20:27)
      at Recording.functionCall (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/Recording.ts:37:32)
      at FileTooLargeError.record (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/recorder.ts:22:26)
      at FileTooLargeError.get message [as message] (src/fingerprint/fileTooLargeError.ts:86:36)
      at stringify (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:27:17)
      at parameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:12:12)
      at optParameter (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/parameter.ts:32:10)
      at makeCallEvent (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/event.ts:20:27)
      at Recording.functionCall (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/Recording.ts:37:32)
      at FileTooLargeError.record (../../../../../.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/recorder.ts:22:26)
      at FileTooLargeError.get message [as message] (src/fingerprint/fileTooLargeError.ts:86:36)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        3.326 s
(Λ) Wrote 2 AppMaps to /home/ahtrotta/projects/appmap/appmap-js/packages/cli/tmp/appmap/jest/Fingerprinter/
```

**Comment by dividedmind** [comment]
Fixed by 6e38a11c259a50bb9df397827a5939c694fbc3f3
