### ISSUE TITLE
`AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value: (0, node_assert_1.default)(this.stream)`

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-node#52]
To reproduce, run the following command in `packages/client` in `appmap-js`:
```
npx appmap-node@latest yarn jest appMap.create.spec.ts
```
I get the following output:
```
(Λ) Running with appmap-node version 2.6.1
(Λ) Detected Jest. Tests will be automatically recorded.
(Λ) Wrote 5 AppMaps to /home/ahtrotta/projects/appmap/appmap-js/packages/client/tmp/appmap/jest/appMap/

 RUNS  test/appMap.create.spec.ts
node:assert:399
    throw err;
    ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, node_assert_1.default)(this.stream)

    at Recording.httpClientRequest (/home/ahtrotta/.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/Recording.ts:80:11)
    at OverriddenClientRequest.<anonymous> (/home/ahtrotta/.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/hooks/http.ts:69:42)
    at OverriddenClientRequest.emit (node:events:513:28)
    at InterceptedRequestRouter.startPlayback (/home/ahtrotta/projects/appmap/appmap-js/node_modules/nock/lib/intercepted_request_router.js:310:11)
    at InterceptedRequestRouter.maybeStartPlayback (/home/ahtrotta/projects/appmap/appmap-js/node_modules/nock/lib/intercepted_request_router.js:262:12)
    at InterceptedRequestRouter.connectSocket (/home/ahtrotta/projects/appmap/appmap-js/node_modules/nock/lib/intercepted_request_router.js:140:12)
    at /home/ahtrotta/projects/appmap/appmap-js/node_modules/nock/lib/intercepted_request_router.js:78:33
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

Node.js v18.16.0
```

**Comment by dividedmind** [comment]
Fixed in 73d993c34bb670ac9fe0da409ae3433e26a26327
